#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/jdbc
#    username: root
#    password: Abhi
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true